version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: articulos-api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data:
